### ISSUE TITLE
How to install the tool on my local nextcloud instance?

### ISSUE THREAD

**Issue by olegme** [smarinier/importer#1]
debian 11.8
php 8.1
nextcloud 28.0.3

Thank you!

**Comment by smarinier** [comment]
Simply install the application manually (ftp or scp) in the nextcloud/apps/ folder.
   - Download the release v0.0.1
   - `tar zxf importer.tar.gz`

You need to have:
    `(your nextcloud)/apps/importer`

Then in admin Applications screen, you activate the application.
Or with command occ:
   `sudo -u www-data ./occ app:enable importer`

(The app works only with occ command by the way )

**Comment by olegme** [comment]
Thank you for the quick answer, but I guess something is still missing:

```
root@supra:/var/www/nextcloud# sudo -u www-data php occ import:import -F /home/olegme/evernote_import/Templates.enex -U olegme -D Notes/Templates -N -v

Simulate import file /home/olegme/evernote_import/Templates.enex (application/enex+xml)
Should import in /olegme/files/Notes/Templates
An unhandled exception has been thrown:
Error: Class "League\HTMLToMarkdown\HtmlConverter" not found in /var/www/nextcloud/apps/importer/lib/EverNote/ENote.php:47
Stack trace:
#0 /var/www/nextcloud/apps/importer/lib/Converter/EnexConverter.php(159): OCA\Importer\EverNote\ENote->getMarkDownContent()
#1 /var/www/nextcloud/apps/importer/lib/Converter/EnexConverter.php(79): OCA\Importer\Converter\EnexConverter->saveNote()
#2 [internal function]: OCA\Importer\Converter\EnexConverter->_stop_element_handler()
#3 /var/www/nextcloud/apps/importer/lib/Converter/EnexConverter.php(201): xml_parse()
#4 /var/www/nextcloud/apps/importer/lib/Command/Import.php(151): OCA\Importer\Converter\EnexConverter->import()
#5 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\Importer\Command\Import->execute()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#10 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/nextcloud/occ(11): require_once('...')

```

**Comment by smarinier** [comment]
Sorry ! Option parameter -U is mandatory. You need to specify who will be the creator of your imported note.

I will fixe it in a new version (tell this is mandatory ;) ).

**Comment by olegme** [comment]
The -U parameter is there, just scroll to the right ;-)

But I assume that a class from some external library is not found - `League\HTMLToMarkdown\HtmlConverter`

I'm not so versed in PHP and hoped you could give me a hint.

Thank you

**Comment by smarinier** [comment]
This file should be in vendor/league/html-to-markdown/src/ folder.

From my side, i've downloaded it and installed it as described in a fresh NC 28 app, then i activated it, and the command works fine.

Did you download the importer tar file (and not the source code) ?

**Comment by olegme** [comment]
I got it running, below are my steps. Feel free to add to README for the benefit of others.

1. Grab `importer.tar.gz` from the Release page on GitHub
2. Place it into the apps directory on the nextcloud server (`/var/ww/nextcloud/apps`)
3. Untar: `tar xvfz importer.tar.gz`
4. Run `occ app:install importer` followed by `occ app:enable importer`

Thank you
